LibreriaMVC/Controllers/EditorialController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyVet.Domain.Dto;
using MyVet.Domain.Services.Interface;
using MyVet.Handlers;
using System.Linq;
using System.Threading.Tasks;
using static Common.Utils.Constant.Const;

namespace MyVet.Controllers
{


    [Authorize]
    [TypeFilter(typeof(CustomExceptionHandler))]
    public class EditorialController : Controller
    {
        #region Attribute
        private readonly IEditorialServices _editorialServices;
        #endregion
        #region Buider
        public EditorialController(IEditorialServices editorialServices)
        {
            _editorialServices = editorialServices;

        }
        #endregion

        #region Methods
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetAllEditorial()
        {
            var user = HttpContext.User;
            string token = user.Claims.FirstOrDefault(x => x.Type == TypeClaims.Token).Value;


            ResponseDto response = await _editorialServices.GetAllEditorial(token);
            return Ok(response);
        }

        [HttpDelete]
        public async Task<IActionResult> DeleteEditorial(int idEditorial)
        {
            var user = HttpContext.User;
            string token = user.Claims.FirstOrDefault(x => x.Type == TypeClaims.Token).Value;


           

            ResponseDto response = await _editorialServices.DeleteEditorial(token,idEditorial);
            return Ok(response);
        }
        [HttpPost]
        public async Task<IActionResult> InsertEditorial(EditorialDto editorialDto)
        {
            var user=HttpContext.User;
            string token = user.Claims.FirstOrDefault(x => x.Type == TypeClaims.Token).Value;
            ResponseDto response = await _editorialServices.InsertEditorial(token,editorialDto);
            return Ok(response);
        }
        [HttpPut]
        public async Task<IActionResult> UpdateEditorial(EditorialDto editorialDto)
        {
            var user = HttpContext.User;
            string token = user.Claims.FirstOrDefault(x => x.Type == TypeClaims.Token).Value;
            ResponseDto response = await _editorialServices.UpdateEditorial(token, editorialDto);
            return Ok(response);
        }



        #endregion

    }
}

LibreriaMVC/Views/Editorial/Index.cshtml
@{
    ViewData["Title"] = "Mis Editoriales";
}

<h1>Listado de Editoriales</h1>


<p>

    <button class="btn btn-primary" onclick="nuevaEditorial()">

        <i class="far fa-building"></i> Nuevo Editorial
    </button>
</p>

<div class="row">

    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Nombre</th>
                <th scope="col">sede</th>
                <th scope="col">Opciones</th>
            </tr>
        </thead>

        <tbody id="cuerpoEditorial"></tbody>
    </table>

</div>



<div class="modal fade" id="modalEditorial" tabindex="1" role="dialog" aria-labelledby="modalEditorialLabel" aria-hidden="true">

    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="idTituloModalEditorial">Crear Editorial</h5>
            </div>
            <div class="modal-body">
                <form>

                    <div class="row">
                        <div class="col-md-6 form-group">
                            <label for="recipient-name" class="col-form-label">Nombre</label>
                            <input type="text" class="form-control" id="txtNameEditorial" placeholder="Nombre Editorial" required>
                        </div>
                        <div class="col-md-6 form-group">
                            <label for="recipient-name" class="col-form-label">Sede</label>
                            <input type="text" class="form-control" id="txtSedeEditorial" placeholder="Info de la Sede" required>
                        </div>
                    </div>

                  



                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">
                    <i class="fas fa-window-close"></i>
                    Cancelar
                </button>
                <button type="button" class="btn btn-success" onclick="guardarEditorial()">
                    <i class="far fa-save"></i>
                    Guardar
                </button>
            </div>
        </div>
    </div>
</div>




@section Scripts{
  @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

<script type="text/javascript" charset="utf-8">
    //var listaPets= JSON.parse('@Json.Serialize(@Model)');
    var listaEditorial= [];
    let idEditorial='';

    $(document).ready(function () {
       getAllEditorial();
   
    });
    function getAllEditorial()
    {
        modalProcesando(true);
        $.ajax({
            url: '@Url.Action("GetAllEditorial", "Editorial")',
            method: 'GET',
            dataType: "json",
            success: function (data) {
                modalProcesando(false);
                listaEditorial=data;
                 //console.log(listaEditorial);
                 if(data.success)
                {
                    listaEditorial=data.result;
                     cargarGridEditorial(listaEditorial);
                    console.log(listaEditorial);
                }else{
                    Swal.fire(
                                'Opps!',
                                data.message,
                                'error');
                }
            
            },
            error: function (xhr, textStatus, errorThrown) {
                    modalProcesando(false);
                    console.error(xhr, textStatus, errorThrown);
                }
         });
    }
    function cargarGridEditorial(data){
        
        $("#cuerpoEditorial").html("");
       
        
        for(var i=0; i<data.length; i++){
            
            console.log(data);
            var tr=`
             <tr>
                <th>`+ data[i].name+ `</th>
                <th> `+ data[i].sede +`</th>
                <td>
              <button  class="btn btn-warning" onclick="editarEditorial(`+ data[i].id +`)"><i class="fas fa-edit"></i> Editar</button>
             <button class="btn btn-danger" onclick="eliminarEditorial(`+ data[i].id +`)"><i class="far fa-trash-alt"></i> Eliminar</button>
                </td>
            </tr>
            `;
            $("#cuerpoEditorial").append(tr);
        }
    }
    function eliminarEditorial(idEditorial)
    {
        console.log("mandó a eliminar", idEditorial);
        Swal.fire({
            title: '¿Confirmar Eliminacion?',
            text: "No podrás revertir esto.!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            cancelButtonText: 'Cancelar',
            confirmButtonText: 'Si, Eliminar!',
        }).then((result) => {
            if (result.isConfirmed) {
                modalProcesando(true);
                //petición
                $.ajax({
                    url: '@Url.Action("DeleteEditorial", "Editorial")',
                    method: 'DELETE',
                    data:{
                        idEditorial:idEditorial
                    },
                    dataType: "json",
                    success: function (data) {
                        modalProcesando(false);
                        console.log(data);
                        if(data.success){
                            console.log("estoy aca");
                            listaEditorial=Object.values(listaEditorial).filter(x=>x.id!=idEditorial);
                            console.log(listaEditorial);
                            console.log("voy despues del filtro");
                         
                            cargarGridEditorial(listaEditorial);
                            Swal.fire(
                                'Eliminado!',
                                data.message,
                                'success');
                        }else{
                            Swal.fire(
                                'Error!',
                                data.message,
                                'error');
                        }
                     },
                     error: function (xhr, textStatus, errorThrown) {
                         modalProcesando(false);
                         console.error(xhr, textStatus, errorThrown);
                     }
                  });
                }
            });
        }
    function nuevaEditorial(){
    
       $('#idTituloModalEditorial').html("Crear Editorial");
       $('#modalEditorial').modal({keyboard:true});
    }
 
   
  
     function guardarEditorial() {

            if (validarForm()) {

                let parametro = {
                  
                    Name: $("#txtNameEditorial").val(),
                  
                    Sede: $("#txtSedeEditorial").val()
                }
                console.log(idEditorial);
                if (idEditorial == '') {
                    modalProcesando(true);
                    $.ajax({
                        url: '@Url.Action("InsertEditorial", "Editorial")',
                        method: 'POST',
                        dataType: "json",
                        data: parametro,
                        success: function (data) {
                            modalProcesando(false);
                            if (data) {
                                $('#modalEditorial').modal('hide');
                                toastMessage('success', 'Editorial Guardada Exitosamente!');
                                getAllEditorial();
                                limpiarForm();
                            } else {
                                toastMessage('error', 'Hubo un error al guardar, por favor intentarlo nuevamente!');
                            }
                        },
                        error: function (xhr, textStatus, errorThrown) {
                            modalProcesando(false);
                            toastMessage('error', 'Hubo un error al guardar, por favor intentarlo nuevamente!');
                            console.error(xhr, textStatus, errorThrown);
                        }
                    });
                } else {
                    
                    parametro.id = idEditorial;
                    modalProcesando(true);
                    $.ajax({
                        url: '@Url.Action("UpdateEditorial", "Editorial")',
                        method: 'PUT',
                        data: parametro,
                        dataType: "json",
                        success: function (data) {
                            modalProcesando(false);

                            if (data) {
                                $('#modalEditorial').modal('hide'); //=>hide: Ocultar
                                limpiarForm();
                                console.log("soy el update")
                                toastMessage('success', 'Editorial Actualizada exitosamente!');
                                getAllEditorial();
                            } else {
                                toastMessage('error', 'Hubo un error al guardar, por favor intentarlo nuevamente!');
                            }
                        },
                        error: function (xhr, textStatus, errorThrown) {
                            modalProcesando(false);
                            toastMessage('error', 'Hubo un error al guardar, por favor intentarlo nuevamente!');
                            console.error(xhr, textStatus, errorThrown);
                        }
                    });
                }
            }
        } 
    function validarForm()
    {
        if($("#txtNameEditorial").val()=='')
        {
                $("#txtNameEditorial").focus();
                toastMessage('warning','El nombre es obligatorio.');
                return false;
        }
        if($("#txtSedeEditorial").val()=='')
        {
                $("#txtSedeEditorial").focus();
                toastMessage('warning','La informacion de la sede es obligatoria.');
                return false;
        }
     
        return true;
    }
    function limpiarForm()
    {
       $("#txtNombreEditorial").val('');
       $("#txtSedeEditorial").val('');
       idEditorial='';
       cargarGridEditorial(listaEditorial);
    }
   
  
    function editarEditorial(id)
    {
        idEditorial=id;
        console.log(idEditorial)
        let editorial= listaEditorial.find(x=>x.id==idEditorial);
      
        $('#txtNameEditorial').val(editorial.name);
   $('#txtSedeEditorial').val(editorial.sede);
       $('#idTituloModalEditorial').html("editar editorial");
       $('#modalEditorial').modal({keyboard:true});
    }
</script>
}