LibreriaMVC/Controllers/AuthController.cs
using Common.Utils.Helpers;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using MyVet.Domain.Dto;
using MyVet.Domain.Dto.RestServices;
using MyVet.Domain.Services.Interface;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using static Common.Utils.Constant.Const;

namespace MyVet.Controllers
{
    public class AuthController : Controller
    {
        //Atributo creado a partir de la interfaz
        private readonly IUserServices _userServices;

        //Se le inyecta el servicio por medio de la instancia de la interfaz
        public AuthController(IUserServices userServices)
        {
            _userServices = userServices; //Le pasamos el valor de esa instancia al atributo global
        }


        //Esta acción llama a la vista
        [HttpGet]
        public IActionResult Login()
        {
            return View(new UserDto()); 
        }

        //Esta accion Verifica  los datos ingresados
        [HttpPost]
        public async Task <IActionResult> Login(UserDto user)
        {
            ResponseDto response = await _userServices.Login(user);

            if (!response.Success)
            {
                ModelState.Clear();
                ModelState.AddModelError(string.Empty, response.Message);
                return View(user);
            }
            else
            {
                TokenDto token = JsonConvert.DeserializeObject<TokenDto>(response.Result.ToString());
                //string idRoles = Utils.GetClaimValue(token.Token, TypeClaims.IdRol);
                //string idUser = Utils.GetClaimValue(token.Token, TypeClaims.IdUser);
                var claims = new List<Claim>
                {
                    new Claim("Token", token.Token),
                    new Claim("Expiration", token.Expiration.ToString()),
                    //new Claim(TypeClaims.IdRol,idRoles),
                    //new Claim(TypeClaims.IdUser,idUser),
                };

                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                var authProperties = new AuthenticationProperties
                {
                    ExpiresUtc = DateTimeOffset.UtcNow.AddMinutes(4),
                    IsPersistent = false,
                };

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                                            new ClaimsPrincipal(claimsIdentity),
                                            authProperties);
                return Redirect("/Home/Index");
            }
        }

        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction(nameof(Login));
        }

        //[HttpGet]
        //public IActionResult Register()
        //{
        //    return View(new UserDto());
        //}

        //[HttpPost]
        //public async Task<IActionResult> Register(UserDto user)
        //{
        //    IActionResult response;

        //    var result = await _userServices.Register(user);
        //    if (!result.IsSuccess)
        //    {
        //        ModelState.Clear();
        //        ModelState.AddModelError(string.Empty, result.Message);
        //        return View(user);
        //    }
        //    else
        //    {
        //        response = RedirectToAction(nameof(Login));
        //    }
        //    return response;
        //}

    }
}

LibreriaMVC/Controllers/AutoresController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyVet.Domain.Dto;
using MyVet.Domain.Dto.Libreria;
using MyVet.Domain.Services.Interface;
using MyVet.Handlers;
using System.Linq;
using System.Threading.Tasks;
using static Common.Utils.Constant.Const;

namespace MyVet.Controllers
{

    [Authorize]
    [TypeFilter(typeof(CustomExceptionHandler))]
    public class AutoresController : Controller
    {
        #region Attribute
        private readonly IAutoresServices _autoresServices;
        #endregion
        #region Buider
        public AutoresController(IAutoresServices autoresServices)
        {
            _autoresServices = autoresServices;

        }
        #endregion

        #region Methods
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetAllAutores()
        {
            var user = HttpContext.User;
            string token = user.Claims.FirstOrDefault(x => x.Type == TypeClaims.Token).Value;


            ResponseDto response = await _autoresServices.GetAllAutores(token);
            return Ok(response);
        }

        [HttpDelete]
        public async Task<IActionResult> DeleteAutor(int idAutor)
        {
            var user = HttpContext.User;
            string token = user.Claims.FirstOrDefault(x => x.Type == TypeClaims.Token).Value;




            ResponseDto response = await _autoresServices.DeleteAutor(token, idAutor);
            return Ok(response);
        }

        [HttpPost]
        public async Task<IActionResult> InsertAutor(InsertAutoresDto autoresDto)
        {
            var user = HttpContext.User;
            string token = user.Claims.FirstOrDefault(x => x.Type == TypeClaims.Token).Value;
            ResponseDto response = await _autoresServices.InsertAutor(token, autoresDto);
            return Ok(response);
        }

        [HttpPut]
        public async Task<IActionResult> UpdateAutor(InsertAutoresDto autoresDto)
        {
            var user = HttpContext.User;
            string token = user.Claims.FirstOrDefault(x => x.Type == TypeClaims.Token).Value;
            ResponseDto response = await _autoresServices.UpdateAutor(token,autoresDto);
            return Ok(response);
        }

        #endregion

    }
}

LibreriaMVC/Controllers/BooksController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MyVet.Domain.Dto;
using MyVet.Domain.Dto.Libreria;
using MyVet.Domain.Services.Interface;
using MyVet.Handlers;
using System.Linq;
using System.Threading.Tasks;
using static Common.Utils.Constant.Const;

namespace MyVet.Controllers
{
    [Authorize]
    [TypeFilter(typeof(CustomExceptionHandler))]
    public class BooksController : Controller
    {
        #region Attribute
        private readonly IBooksServices _booksServices;
        #endregion
        #region Buider
        public BooksController(IBooksServices  booksServices)
        {
            _booksServices = booksServices;

        }
        #endregion

        #region Methods
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetAllBooks()
        {
            var user = HttpContext.User;
            string token = user.Claims.FirstOrDefault(x => x.Type == TypeClaims.Token).Value;


            ResponseDto response = await _booksServices.GetAllBooks(token);
            return Ok(response);
        }

        [HttpDelete]
        public async Task<IActionResult> DeleteBooks(int idBooks)
        {
            var user = HttpContext.User;
            string token = user.Claims.FirstOrDefault(x => x.Type == TypeClaims.Token).Value;




            ResponseDto response = await _booksServices.DeleteBook(token, idBooks);
            return Ok(response);
        }

        [HttpPost]
        public async Task<IActionResult> InsertBook(InsertBooksDto booksDto)
        {
            var user = HttpContext.User;
            string token = user.Claims.FirstOrDefault(x => x.Type == TypeClaims.Token).Value;
            ResponseDto response = await _booksServices.InsertBook(token, booksDto);
            return Ok(response);
        }

        [HttpPut]
        public async Task<IActionResult> UpdateBook(AlterBooksDto booksDto)
        {
            var user = HttpContext.User;
            string token = user.Claims.FirstOrDefault(x => x.Type == TypeClaims.Token).Value;
            ResponseDto response = await _booksServices.UpdateBook(token, booksDto);
            return Ok(response);
        }

        #endregion

    }

}

LibreriaMVC/Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Mvc;
using MyVet.Domain.Dto;
using MyVet.Domain.Services.Interface;
using System.Linq;
using System.Threading.Tasks;
using static Common.Utils.Constant.Const;

namespace LibreriaMVC.Controllers
{
    public class UsuariosController : Controller
    {
        #region Attribute
        private readonly IUserServices _userServices;
        #endregion
        #region Buider
        public UsuariosController(IUserServices usersServices)
        {
            _userServices= usersServices;

        }
        #endregion

        #region Methods
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetAllUsuarios()
        {
            var user = HttpContext.User;
            string token = user.Claims.FirstOrDefault(x => x.Type == TypeClaims.Token).Value;


            ResponseDto response = await _userServices.GetAllUsers(token);
            return Ok(response);
        }
        #endregion
    }
}

LibreriaMVC/Views/Shared/_Layout.cshtml
@using Common.Utils.Enums
@using Microsoft.AspNetCore.Identity
@using static Common.Utils.Constant.Const
@{

}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyVet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
          integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />
</head>
<body>

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyLibrary</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav">
                        @if (User != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index" title="Manage">Hola @User.Identity.Name!</a>
                            </li>
                            <li class="nav-item">
                                <form class="form-inline" asp-area="" asp-controller="Auth" asp-action="Logout" method="get">
                                    <button type="submit" class="nav-link btn btn-link text-dark"> <i class="fas fa-sign-out-alt"></i>  Salir</button>
                                </form>
                            </li>
                        }
                    </ul>

                    <ul class="navbar-nav flex-grow-1">
                        @* <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">Libros</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Autores" asp-action="Index">Autores</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Editorial" asp-action="Index">Editoriales</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Index">Usuarios</a>
                        </li>
                       
                           
                           
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div class="modal fade" id="container-modal-procesando" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-sm modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-body" style="text-align:center;font-weight:bold">
                    <p id="mensaje-modal-procesando">Por favor espere</p>
                    <div align="center"><img width="100%" src="~/img/loading-97.gif"></div>
                </div>
            </div>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MyVet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/js/all.min.js"
            integrity="sha512-Tn2m0TIpgVyTzzvmxLNuqbSJH3JP8jm+Cy3hvHrW7ndTDcJ1w5mBiksqDBb8GpE2ksktFvDB/ykZ0mDpsZj20w=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer"></script>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.3.6/dist/sweetalert2.all.min.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

<script>
    $(document).ready(function () {
     });
     function modalProcesando(desplegar)
     {
         if(desplegar)
         {
            $("#container-modal-procesando").modal({ backdrop: 'static', keyboard: false });
         }else{
            setTimeout(function () {
                    $('#container-modal-procesando').modal('hide');
            }, 500);
         }
     }
     function toastMessage(type,message)
     {
         const Toast = Swal.mixin({
             toast: true,
             position: 'top-end',
             showConfirmButton: false,
             timer: 3000,
             timerProgressBar: true,
             didOpen: (toast) => {
                 toast.addEventListener('mouseenter', Swal.stopTimer)
                 toast.addEventListener('mouseleave', Swal.resumeTimer)
             }});
             Toast.fire({
                 icon: type,
                 title: message
             });
     }
</script>

LibreriaMVC/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyVet</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MyVet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>